
package vista;

import controlador.PrgArreglosBidi;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Franklin
 */
public class WinArreglosBidi extends javax.swing.JInternalFrame {
    
    PrgArreglosBidi refPrgArreglosBidi;
    
    public WinArreglosBidi() {
        initComponents();
        refPrgArreglosBidi = new PrgArreglosBidi();
        personalizarEncabezados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        btnGuardarIngre = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaActualizadaIngre = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnMostrarIngre = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btnInfoArregloBidimensional = new javax.swing.JButton();
        btnInfoUso = new javax.swing.JButton();
        btnDataActualizadaIngre = new javax.swing.JButton();
        btnInfoGuardar = new javax.swing.JButton();
        btnInfoMostrarIngre = new javax.swing.JButton();
        btnInfoOrganizacionArregloBidi = new javax.swing.JButton();
        txtNota2 = new javax.swing.JTextField();
        btnDataOriginalIngre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPos = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaActualizadaElim = new javax.swing.JTable();
        btnMostrarElim = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        btnDataActualizadaElim = new javax.swing.JButton();
        btnInfoEliminar = new javax.swing.JButton();
        btnInfoMostrarElim = new javax.swing.JButton();
        btnDataOriginalElim = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("ARREGLOS BIDIMENSIONALES");

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nota 1:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nota 2:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nota 3:");

        txtNota1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNota1.setText("16");

        txtNota3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNota3.setText("16");

        btnGuardarIngre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGuardarIngre.setText("GUARDAR");
        btnGuardarIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarIngreActionPerformed(evt);
            }
        });

        tablaActualizadaIngre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaActualizadaIngre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nota 1", "Nota 2", "Nota 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActualizadaIngre.setRowHeight(30);
        jScrollPane3.setViewportView(tablaActualizadaIngre);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));

        btnMostrarIngre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMostrarIngre.setText("MOSTRAR");
        btnMostrarIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarIngreActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 0));
        jLabel26.setText("ARREGLOS BIDIMENSIONALES");

        btnInfoArregloBidimensional.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInfoArregloBidimensional.setText("¿Qué es un arreglo bidimensional? ");
        btnInfoArregloBidimensional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoArregloBidimensionalActionPerformed(evt);
            }
        });

        btnInfoUso.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInfoUso.setText("¿Por qué se usan? ");
        btnInfoUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoUsoActionPerformed(evt);
            }
        });

        btnDataActualizadaIngre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDataActualizadaIngre.setText("Data actualizada");
        btnDataActualizadaIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActualizadaIngreActionPerformed(evt);
            }
        });

        btnInfoGuardar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInfoGuardar.setText("¿Qué hace el botón GUARDAR?");
        btnInfoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoGuardarActionPerformed(evt);
            }
        });

        btnInfoMostrarIngre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInfoMostrarIngre.setText("¿Qué hace el botón MOSTRAR?");
        btnInfoMostrarIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoMostrarIngreActionPerformed(evt);
            }
        });

        btnInfoOrganizacionArregloBidi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInfoOrganizacionArregloBidi.setText("¿Cómo se organizan en filas y columnas?");
        btnInfoOrganizacionArregloBidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoOrganizacionArregloBidiActionPerformed(evt);
            }
        });

        txtNota2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNota2.setText("16");

        btnDataOriginalIngre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDataOriginalIngre.setText("Data Original");
        btnDataOriginalIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataOriginalIngreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(726, 726, 726)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNota2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNota1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardarIngre)
                            .addComponent(btnMostrarIngre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInfoGuardar)
                            .addComponent(btnInfoMostrarIngre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnInfoArregloBidimensional)
                        .addGap(18, 18, 18)
                        .addComponent(btnInfoOrganizacionArregloBidi)
                        .addGap(18, 18, 18)
                        .addComponent(btnInfoUso))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDataOriginalIngre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDataActualizadaIngre))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfoArregloBidimensional)
                    .addComponent(btnInfoUso)
                    .addComponent(btnInfoOrganizacionArregloBidi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarIngre)
                            .addComponent(btnInfoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarIngre)
                            .addComponent(btnInfoMostrarIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDataActualizadaIngre)
                    .addComponent(btnDataOriginalIngre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ingresos", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 158, 158));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ingrese el N° de Posición:");

        txtPos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPos.setText("2");

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tablaActualizadaElim.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablaActualizadaElim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaActualizadaElim.setRowHeight(30);
        jScrollPane4.setViewportView(tablaActualizadaElim);

        btnMostrarElim.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMostrarElim.setText("MOSTRAR");
        btnMostrarElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarElimActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 0));
        jLabel27.setText("ARREGLOS BIDIMENSIONALES");

        btnDataActualizadaElim.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDataActualizadaElim.setText("Data Actualizada ");
        btnDataActualizadaElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActualizadaElimActionPerformed(evt);
            }
        });

        btnInfoEliminar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInfoEliminar.setText("¿Qué hace el botón ELIMINAR?");
        btnInfoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoEliminarActionPerformed(evt);
            }
        });

        btnInfoMostrarElim.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInfoMostrarElim.setText("¿Qué hace el botón MOSTRAR?");
        btnInfoMostrarElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoMostrarElimActionPerformed(evt);
            }
        });

        btnDataOriginalElim.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDataOriginalElim.setText("Data Original");
        btnDataOriginalElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataOriginalElimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMostrarElim)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInfoEliminar)
                            .addComponent(btnInfoMostrarElim)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnDataOriginalElim, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDataActualizadaElim)))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnInfoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarElim)
                    .addComponent(btnInfoMostrarElim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDataOriginalElim)
                    .addComponent(btnDataActualizadaElim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminación", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoMostrarElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoMostrarElimActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué hace el botón MOSTRAR en Eliminación?",
            " \n El botón MOSTRAR actualiza la tabla de 'Data Actualizada' \n" +
            " con los registros actuales después de realizar una \n" +
            " eliminación. \n\n" +
            " Permite visualizar cómo quedó la matriz de notas sin el \n" +
            " estudiante eliminado. \n",
            "imagenes/mostrar_eliminacion_notas.png");
    }//GEN-LAST:event_btnInfoMostrarElimActionPerformed

    private void btnInfoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoEliminarActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué hace el botón ELIMINAR?",
            " El botón ELIMINAR busca la posición ingresada por \n" +
            " el usuario en la matriz de notas. \n\n" +
            " Si la posición existe, elimina esa fila completa \n" +
            " (las tres notas del estudiante). \n\n" +
            " Luego, las filas posteriores se recorren hacia \n" +
            " arriba para mantener la estructura sin huecos. \n\n" +
            " Así la matriz queda compacta y actualizada. ",
            "imagenes/eliminar_notas.png");
    }//GEN-LAST:event_btnInfoEliminarActionPerformed

    private void btnDataActualizadaElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActualizadaElimActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué es la Data Actualizada?",
            " \n La Data Actualizada muestra cómo queda la matriz de \n" +
            " notas después de eliminar el registro seleccionado. \n\n" +
            " Aquí se ve la tabla reorganizada, sin la fila \n" +
            " eliminada. \n ",
            "imagenes/mostrar_eliminacion_notas.png");
    }//GEN-LAST:event_btnDataActualizadaElimActionPerformed

    private void btnMostrarElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarElimActionPerformed
        refPrgArreglosBidi.mostrarDatos(tablaActualizadaElim);
    }//GEN-LAST:event_btnMostrarElimActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int pos = Integer.parseInt(txtPos.getText());
        refPrgArreglosBidi.eliminarPorPosicion(pos);

        txtPos.setText("");
        txtPos.requestFocus();

        refPrgArreglosBidi.mostrarDatos(tablaActualizadaIngre);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInfoMostrarIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoMostrarIngreActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué hace el botón MOSTRAR?",
            " \n El botón MOSTRAR recorre todas las filas del \n" +
            " arreglo bidimensional y actualiza la tabla \n" +
            " con las notas de cada estudiante.  \n\n" +
            " Esto permite visualizar la lista completa \n" +
            " de registros guardados. \n",
            "imagenes/mostrar_notas.png");
    }//GEN-LAST:event_btnInfoMostrarIngreActionPerformed

    private void btnInfoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoGuardarActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué hace el botón GUARDAR?",
            " \n El botón GUARDAR toma las tres notas ingresadas por el usuario \n" +
            " y las guarda como una nueva fila en el arreglo bidimensional. \n\n" +
            " Cada nota se coloca en su respectiva columna: Nota 1, \n" +
            " Nota 2 y Nota 3. \n\n" +
            " Así se añade un nuevo estudiante con sus notas. \n ",
            "imagenes/guardar_notas.png");
    }//GEN-LAST:event_btnInfoGuardarActionPerformed

    private void btnDataActualizadaIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActualizadaIngreActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué es la Data Actualizada?",
            " \n La Data Actualizada muestra cómo queda el arreglo \n" +
            " bidimensional después de guardar un nuevo \n" +
            " registro. \n\n" +
            " Aquí se ve la tabla con el nuevo estudiante \n" +
            " añadido al final. \n",
            "imagenes/data_actualizada_notas.png");
    }//GEN-LAST:event_btnDataActualizadaIngreActionPerformed

    private void btnInfoUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoUsoActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Por qué se usan los arreglos bidimensionales?",
            " Se usan para organizar información relacionada de forma \n" +
            " compacta y ordenada. \n\n" +
            " En lugar de tener tres arreglos separados para cada nota, \n" +
            " usamos una sola matriz donde cada fila contiene todas \n" +
            " las notas de un estudiante. \n\n" +
            " Esto facilita el manejo, visualización y actualización \n" +
            " de los datos. ",
            "imagenes/arreglo_bidimensional_notas.png");
    }//GEN-LAST:event_btnInfoUsoActionPerformed

    private void btnInfoArregloBidimensionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoArregloBidimensionalActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué es un arreglo bidimensional?",
            " Un arreglo bidimensional es una estructura que \n" +
            " guarda datos en forma de tabla. \n\n" +
            " Se organiza en filas y columnas, como una hoja \n" +
            " de cálculo. \n\n" +
            " En este caso, cada fila representa a un estudiante \n" + 
            " y cada columna una nota. \n\n" + 
            " Ejemplo: notas[2][1] → significa estudiante 3, nota 2.",
            "imagenes/arreglo_bidimensional_notas.png");
    }//GEN-LAST:event_btnInfoArregloBidimensionalActionPerformed

    private void btnMostrarIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarIngreActionPerformed
        refPrgArreglosBidi.mostrarDatos(tablaActualizadaIngre);
    }//GEN-LAST:event_btnMostrarIngreActionPerformed

    private void btnGuardarIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngreActionPerformed
        float n1 = Float.parseFloat(txtNota1.getText());
        float n2 = Float.parseFloat(txtNota2.getText());
        float n3 = Float.parseFloat(txtNota3.getText());
        refPrgArreglosBidi.guardarDatos(n1, n2, n3);
        JOptionPane.showMessageDialog(null, "Notas insertadas correctamente");

        txtNota1.setText("");
        txtNota2.setText("");
        txtNota3.setText("");
        txtNota1.requestFocus();

        refPrgArreglosBidi.mostrarDatos(tablaActualizadaElim);
    }//GEN-LAST:event_btnGuardarIngreActionPerformed

    private void btnInfoOrganizacionArregloBidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoOrganizacionArregloBidiActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Cómo se organizan en filas y columnas?",
            " \n En un arreglo bidimensional, cada posición se identifica con dos \n" +
            " índices: el primero indica la fila y el segundo la columna. \n\n" +
            " Ejemplo: la fila 0 contiene las tres notas del primer estudiante, \n " +
            " y la fila 1 contiene las notas del segundo estudiante. \n",
            "imagenes/arreglo_bidimensional_notas.png");                               
    }//GEN-LAST:event_btnInfoOrganizacionArregloBidiActionPerformed

    private void btnDataOriginalIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataOriginalIngreActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué es la Data Original?",
            " \n La Data Original muestra los registros que ya \n" +
            " están guardados en el arreglo bidimensional. \n\n" +
            " Es la información base antes de realizar \n" +
            " nuevas inserciones. \n ",
            "imagenes/data_original_notas.png");
    }//GEN-LAST:event_btnDataOriginalIngreActionPerformed

    private void btnDataOriginalElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataOriginalElimActionPerformed
        refPrgArreglosBidi.mostrarInfo(
            this,
            "¿Qué es la Data Original?",
            " \n La Data Original muestra todos los registros \n" +
            " guardados en la matriz de notas antes de \n" +
            " realizar cualquier eliminación. \n\n" +
            " Es la base de comparación para ver los \n" +
            " cambios posteriores \n",
            "imagenes/data_original_eliminacion.png");
    }//GEN-LAST:event_btnDataOriginalElimActionPerformed
    
    private void configurarTabla(JTable tabla){
        tabla.getTableHeader().setFont(new Font("Arial", Font.BOLD, 16));
        tabla.getTableHeader().setPreferredSize(new Dimension(0, 30));
    }
    
    private void personalizarEncabezados(){
        configurarTabla(tablaActualizadaIngre);
        refPrgArreglosBidi.mostrarDatos(tablaActualizadaIngre);
        
        configurarTabla(tablaActualizadaElim);
        refPrgArreglosBidi.mostrarDatos(tablaActualizadaElim);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataActualizadaElim;
    private javax.swing.JButton btnDataActualizadaIngre;
    private javax.swing.JButton btnDataOriginalElim;
    private javax.swing.JButton btnDataOriginalIngre;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarIngre;
    private javax.swing.JButton btnInfoArregloBidimensional;
    private javax.swing.JButton btnInfoEliminar;
    private javax.swing.JButton btnInfoGuardar;
    private javax.swing.JButton btnInfoMostrarElim;
    private javax.swing.JButton btnInfoMostrarIngre;
    private javax.swing.JButton btnInfoOrganizacionArregloBidi;
    private javax.swing.JButton btnInfoUso;
    private javax.swing.JButton btnMostrarElim;
    private javax.swing.JButton btnMostrarIngre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaActualizadaElim;
    private javax.swing.JTable tablaActualizadaIngre;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtPos;
    // End of variables declaration//GEN-END:variables
}
